name: Puppeteer Scraper Workflow

# Trigger the workflow on every push or manual run
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-puppeteer:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16"

    - name: Install Dependencies
      run: npm install

    - name: Run Puppeteer
      run: node index.js
